import re
q=open("_fd_AAPL_10Q_FY26Q3.txt",encoding="utf-8",errors="ignore").read()
print("="*100)
print("FACT: unconditional purchase obligations schedule")
print(" 10-K FY2025 (as of 2025-09-27, acc 0000320193-25-000079):")
print("   2026 4,752 | 2027 3,708 | 2028 1,981 | 2029 1,306 | 2030 788 | Thereafter 773 | TOTAL 13,308")
print(" 10-Q Q3FY26 (as of 2026-06-27, acc 0000320193-26-000020):")
print("   2026(rem 3mo) 2,053 | 2027 7,652 | 2028 6,406 | 2029 5,421 | 2030 5,481 | Thereafter 615 | TOTAL 27,628")
a={2027:3708,2028:1981,2029:1306,2030:788}; b={2027:7652,2028:6406,2029:5421,2030:5481}
for y in a: print(f"   FY{y}: {a[y]:,} -> {b[y]:,}  ({b[y]/a[y]:.1f}x)")
print(f"   TOTAL: 13,308 -> 27,628  (+{27628-13308:,}M, +{100*(27628/13308-1):.0f}%) in 3 quarters")
print()
print("FACT: intangibles & inventory (same two filings)")
print("   gross intangibles 24,950 -> 38,220  (+13,270M, +53%)")
print("   net intangibles   13,301 -> 25,417  (+12,116M, +91%)")
print("   current portion    2,208 ->  5,075  (+130%)  <- short-lived licensed rights")
print("   inventories: components 2,124 -> 7,645 (+260%); total 5,718 -> 11,092 (+94%)")
print()
# cash flow
i=q.find("Cash generated by operating activities")
while i>0:
    seg=" ".join(q[max(0,i-2600):i+300].split())
    if "Depreciation" in seg: print("### 9M CASH FLOW EXCERPT:\n",seg[-2400:]); break
    i=q.find("Cash generated by operating activities",i+1)
